/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Origin = "source" | "ai_generated";
export type Text = string;
export type CommonMistake = string;
export type Concept1 = string;
export type Caption = string;
/**
 * Mermaid source (flowchart, timeline or mindmap)
 */
export type Mermaid = string;
export type Type = "none" | "process" | "cycle" | "hierarchy" | "comparison" | "timeline" | "cause_effect";
export type Difficulty = "easy" | "medium" | "hard";
export type Origin1 = "source" | "ai_generated";
/**
 * Segment ids; empty for AI-generated examples
 */
export type SourceRefs = string[];
export type Text1 = string;
export type Examples = Example[];
export type HowItWorks = string[];
export type Id = string;
export type Key = string;
/**
 * Level 3, Go Deeper: more detail for curious students
 */
export type Deeper = string;
/**
 * Level 1, Explain Like I'm New: very simple
 */
export type New = string;
/**
 * Level 2, Understand It: normal explanation for the chosen level
 */
export type Understand = string;
export type LikelyOnTest = boolean;
export type Prerequisites = string[];
export type Flags = string[];
export type Score = number | null;
export type A = string;
export type Q = string;
export type QuickCheck = QuickCheck1[];
export type SourceRefs1 = string[];
export type TeacherEmphasis = boolean;
export type Title = string;
export type WhyItMatters = string;
export type Concepts = Concept[];
export type Id1 = string;
export type Kind =
  "definition" | "date" | "name" | "event" | "number" | "rule" | "exception" | "cause_effect" | "comparison" | "other";
export type Quote = string;
export type SourceRefs2 = string[];
export type TeacherEmphasis1 = boolean;
export type Text2 = string;
export type Verified = boolean;
export type Facts = Fact[];
export type Back = string;
export type Front = string;
export type Id2 = string;
export type SourceRefs3 = string[];
export type Flashcards = Flashcard[];
export type Id3 = string;
export type Latex = string;
export type Meaning = string;
export type Quote1 = string | null;
export type SourceRefs4 = string[];
export type Verified1 = boolean;
export type Formulas = Formula[];
export type Level = "middle_school" | "high_school" | "honors" | "ap" | "college_intro";
export type NotCovered = string[];
export type Objectives = string[];
export type Overview = string | null;
export type Answer = string;
export type ConceptId = string | null;
export type Explanation = string;
export type Id4 = string;
export type Options = string[];
export type Prompt = string;
export type SourceRefs5 = string[];
export type Type1 = "recall" | "understanding" | "application" | "comparison" | "scenario" | "test_style";
export type Questions = Question[];
export type Explanation1 = string;
export type From = string;
export type To = string;
export type Type2 = string;
export type Relationships = Relationship[];
export type ReviewChecklist = string[];
export type SchemaVersion = number;
export type Summary = string | null;
export type Title1 = string;
export type Topics = string[];
export type Definition = string;
export type Example1 = string | null;
export type Id5 = string;
export type Quote2 = string | null;
export type SourceRefs6 = string[];
export type Term = string;
export type Verified2 = boolean;
export type Vocabulary = VocabItem[];
export type Warnings = string[];

export interface StudyGuideContent {
  concepts?: Concepts;
  facts?: Facts;
  flashcards?: Flashcards;
  formulas?: Formulas;
  level: Level;
  not_covered?: NotCovered;
  objectives?: Objectives;
  overview?: Overview;
  questions?: Questions;
  relationships?: Relationships;
  review_checklist?: ReviewChecklist;
  schema_version?: SchemaVersion;
  summary?: Summary;
  title: Title1;
  topics?: Topics;
  vocabulary?: Vocabulary;
  warnings?: Warnings;
}
/**
 * This interface was referenced by `StudyGuideContent`'s JSON-Schema
 * via the `definition` "Concept".
 */
export interface Concept {
  analogy?: Analogy | null;
  common_mistake: CommonMistake;
  concept: Concept1;
  diagram?: Diagram | null;
  difficulty: Difficulty;
  examples: Examples;
  how_it_works: HowItWorks;
  id: Id;
  key: Key;
  levels?: Levels | null;
  likely_on_test?: LikelyOnTest;
  prerequisites: Prerequisites;
  quality?: Quality;
  quick_check: QuickCheck;
  source_refs: SourceRefs1;
  teacher_emphasis?: TeacherEmphasis;
  title: Title;
  why_it_matters: WhyItMatters;
}
/**
 * This interface was referenced by `StudyGuideContent`'s JSON-Schema
 * via the `definition` "Analogy".
 */
export interface Analogy {
  origin: Origin;
  text: Text;
}
/**
 * This interface was referenced by `StudyGuideContent`'s JSON-Schema
 * via the `definition` "Diagram".
 */
export interface Diagram {
  caption: Caption;
  mermaid: Mermaid;
  type: Type;
}
/**
 * This interface was referenced by `StudyGuideContent`'s JSON-Schema
 * via the `definition` "Example".
 */
export interface Example {
  origin: Origin1;
  source_refs: SourceRefs;
  text: Text1;
}
/**
 * This interface was referenced by `StudyGuideContent`'s JSON-Schema
 * via the `definition` "Levels".
 */
export interface Levels {
  deeper: Deeper;
  new: New;
  understand: Understand;
}
/**
 * This interface was referenced by `StudyGuideContent`'s JSON-Schema
 * via the `definition` "Quality".
 */
export interface Quality {
  flags?: Flags;
  score?: Score;
}
/**
 * This interface was referenced by `StudyGuideContent`'s JSON-Schema
 * via the `definition` "QuickCheck".
 */
export interface QuickCheck1 {
  a: A;
  q: Q;
}
/**
 * This interface was referenced by `StudyGuideContent`'s JSON-Schema
 * via the `definition` "Fact".
 */
export interface Fact {
  id: Id1;
  kind: Kind;
  quote: Quote;
  source_refs: SourceRefs2;
  teacher_emphasis?: TeacherEmphasis1;
  text: Text2;
  verified?: Verified;
}
/**
 * This interface was referenced by `StudyGuideContent`'s JSON-Schema
 * via the `definition` "Flashcard".
 */
export interface Flashcard {
  back: Back;
  front: Front;
  id: Id2;
  source_refs: SourceRefs3;
}
/**
 * This interface was referenced by `StudyGuideContent`'s JSON-Schema
 * via the `definition` "Formula".
 */
export interface Formula {
  id: Id3;
  latex: Latex;
  meaning: Meaning;
  quote?: Quote1;
  source_refs: SourceRefs4;
  verified?: Verified1;
}
/**
 * This interface was referenced by `StudyGuideContent`'s JSON-Schema
 * via the `definition` "Question".
 */
export interface Question {
  answer: Answer;
  concept_id: ConceptId;
  explanation: Explanation;
  id: Id4;
  options: Options;
  prompt: Prompt;
  source_refs: SourceRefs5;
  type: Type1;
}
/**
 * This interface was referenced by `StudyGuideContent`'s JSON-Schema
 * via the `definition` "Relationship".
 */
export interface Relationship {
  explanation: Explanation1;
  from: From;
  to: To;
  type: Type2;
}
/**
 * This interface was referenced by `StudyGuideContent`'s JSON-Schema
 * via the `definition` "VocabItem".
 */
export interface VocabItem {
  definition: Definition;
  example?: Example1;
  id: Id5;
  quote?: Quote2;
  source_refs: SourceRefs6;
  term: Term;
  verified?: Verified2;
}
