import type { StudyGuideContent } from "@/lib/types";

/** A small finished guide in the shape the API returns. */
export const guide: StudyGuideContent = {
  schema_version: 1,
  title: "Photosynthesis",
  level: "high_school",
  topics: ["What plants need", "Light reactions"],
  overview: "Plants make their own food using light.",
  objectives: ["Explain what photosynthesis is."],
  vocabulary: [
    {
      id: "v1",
      term: "Chlorophyll",
      definition: "Green pigment that captures light.",
      example: "Leaves are green because of it.",
      quote: "green pigment",
      verified: true,
      source_refs: ["p2-s1"],
    },
  ],
  concepts: [
    {
      id: "c1",
      key: "inputs",
      title: "Inputs and outputs",
      difficulty: "easy",
      prerequisites: [],
      concept: "Plants take in **carbon dioxide** and water.",
      why_it_matters: "It feeds almost every food chain.",
      how_it_works: ["Roots take in water.", "Leaves take in carbon dioxide."],
      examples: [
        { text: "A tomato plant in a sunny window grows faster.", origin: "ai_generated", source_refs: [] },
        { text: "The textbook's bean plant experiment.", origin: "source", source_refs: ["p1-s2"] },
      ],
      analogy: { text: "Like a solar-powered kitchen.", origin: "ai_generated" },
      common_mistake: "Thinking plants get their food from the soil.",
      quick_check: [{ q: "What gas do plants take in?", a: "Carbon dioxide." }],
      levels: null,
      diagram: null,
      source_refs: ["p1-s1"],
    },
    {
      id: "c2",
      key: "light",
      title: "Light reactions",
      difficulty: "hard",
      prerequisites: ["inputs"],
      teacher_emphasis: true,
      concept: "Light splits water.",
      why_it_matters: "It makes the energy the plant stores.",
      how_it_works: ["Light hits chlorophyll."],
      examples: [],
      analogy: null,
      common_mistake: "Thinking oxygen comes from carbon dioxide.",
      quick_check: [],
      levels: {
        new: "Light breaks water apart.",
        understand: "Light energy splits water.",
        deeper: "Photosystem II.",
      },
      diagram: null,
      source_refs: ["d2-p3-s1"],
    },
  ],
  facts: [
    {
      id: "f1",
      text: "Oxygen is released.",
      kind: "rule",
      quote: "oxygen is released",
      verified: false,
      source_refs: ["p1-s1"],
    },
  ],
  formulas: [],
  relationships: [{ from: "inputs", to: "light", type: "enables", explanation: "Water is needed first." }],
  summary: "Plants turn light into sugar.",
  questions: [
    {
      id: "q1",
      type: "recall",
      prompt: "Which pigment captures light?",
      options: ["Chlorophyll", "Glucose"],
      answer: "Chlorophyll",
      explanation: "Chlorophyll absorbs light.",
      concept_id: "c1",
      source_refs: ["p2-s1"],
    },
    {
      id: "q2",
      type: "application",
      prompt: "Why do plants in the dark stop growing?",
      options: [],
      answer: "No light energy for photosynthesis.",
      explanation: "Light powers the process.",
      concept_id: "c2",
      source_refs: [],
    },
  ],
  flashcards: [
    { id: "k1", front: "Chlorophyll", back: "Green pigment", source_refs: [] },
    { id: "k2", front: "Glucose", back: "Sugar", source_refs: [] },
  ],
  review_checklist: ["I can explain photosynthesis."],
  not_covered: ["The Calvin cycle."],
  warnings: [],
};
